using System.Collections.Generic;
using Godot;
using UnitSport.Audio;
using UnitSport.Avatar;

namespace UnitSport.Player;

// GENERATED by tools/motorbikes/gen_catalog.py from docs/data/*_specs.json (#410). Do not edit by hand:
// change the dataset or the script and run it again. Append-only, like the rest of the catalog.
public static partial class MotorbikeCatalog
{
    /// <summary>The bikes from the datasets, after the hand-written entries.</summary>
    private static IEnumerable<MotorbikeSpec> Imported() => new[]
    {
        // ---- 94 ----
        // Yamaha FZS600 Fazer (1998-01). docs/data/yamaha_fazer_r3_tmax_specs.json "FZS600-1998" (FZS600 Fazer (5DM1/5DM4, Fazer S 2000+)).
        // 599 cc inline four, 96 PS at 11,500 rpm, 61 N·m at 9,500; 6 gears 2.846-1.083, primary 1.700, final 3.554; kerb 209 kg; wheelbase 1415 mm; rake 24.0°, trail 88 mm; 110/70ZR17 + 160/60ZR17.
        // Reference: 217 km/h (claimed (Wikipedia, 135 mph; ultimatespecs lists 225 km/h)), 0-100 - s.
        // https://en.wikipedia.org/wiki/Yamaha_FZS600_Fazer
        // https://www.ultimatespecs.com/motorcycles-specs/yamaha/yamaha-fzs-600-fazer-1998
        // Assumed: redline 13,000; kerb 209 kg = dry 189 + 20 kg of fluids; gear ratios borrowed from FZ6-2004 (spread only: the overall gearing is fitted below); primary 1.700 and final 3.554: the overall top gear fitted to 217 km/h at 105% of the peak-power rpm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.46 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1300, launch 6300; livery from "metallic blue with silver-grey lower fairing and black frame (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha FZS600 Fazer (1998-01)",
            Brand = "Yamaha", Family = "Fazer",
            Blurb = "599 cc inline four, 96 PS, 209 kg, half fairing, upright",
            Engine = EngineLayout.Inline4Bike,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.InlineFour,
                Wheelbase = 1.415f, RakeDeg = 24f, Trail = 0.088f, ForkLength = 0.68f,
                FrontTyre = "110/70ZR17", RearTyre = "160/60ZR17", FrontTravel = 0.135f, RearTravel = 0.135f,
                FrontDiscs = 2, FrontDiscMm = 298f, TankLitres = 18f,
                Seat = new Vector3(0, 0.79f, -0.22f), Grip = new Vector3(0.38f, 1.01f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.08f, 0.22f, 0.7f), Trim = new Color(0.9f, 0.9f, 0.92f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "not verified",
            WetMass = 209f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.46f, BrakeDecel = 9.5f,
            IdleRpm = 1300f, PeakRpm = 11500f, Redline = 13000f, LaunchRpm = 6300f,
            Torque = new (float, float)[] { (1300f, 33.6f), (4750f, 50f), (9500f, 61f), (10500f, 61f), (11500f, 58.6f), (13000f, 49.8f) },
            Gears = new[] { 2.846f, 1.947f, 1.556f, 1.333f, 1.19f, 1.083f }, Primary = 1.7f, FinalDrive = 3.5538f,
            RefZeroTo100 = 0f, RefTopKmh = 217f,
        },
        // ---- 95 ----
        // Yamaha FZS600 Fazer (2002-03). docs/data/yamaha_fazer_r3_tmax_specs.json "FZS600-2002" (FZS600 Fazer Foxeye (5RT1)).
        // 599 cc inline four, 96 PS at 11,500 rpm, 61 N·m at 9,500; 6 gears 2.846-1.083, primary 1.700, final 3.554; kerb 209 kg; wheelbase 1415 mm; rake 24.0°, trail 88 mm; 110/70ZR17 + 160/60ZR17.
        // Reference: 217 km/h (claimed (Wikipedia, 135 mph; ultimatespecs lists 225 km/h)), 0-100 - s.
        // https://en.wikipedia.org/wiki/Yamaha_FZS600_Fazer
        // https://www.ultimatespecs.com/motorcycles-specs/yamaha/yamaha-fzs-600-fazer-1998
        // Assumed: redline 13,000; kerb 209 kg = dry 189 + 20 kg of fluids; gear ratios borrowed from FZ6-2004 (spread only: the overall gearing is fitted below); primary 1.700 and final 3.554: the overall top gear fitted to 217 km/h at 105% of the peak-power rpm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.46 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1300, launch 6300; livery from "metallic silver/grey with dark frame and silver wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha FZS600 Fazer (2002-03)",
            Brand = "Yamaha", Family = "Fazer",
            Blurb = "599 cc inline four, 96 PS, 209 kg, half fairing, upright",
            Engine = EngineLayout.Inline4Bike,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.InlineFour,
                Wheelbase = 1.415f, RakeDeg = 24f, Trail = 0.088f, ForkLength = 0.68f,
                FrontTyre = "110/70ZR17", RearTyre = "160/60ZR17", FrontTravel = 0.135f, RearTravel = 0.135f,
                FrontDiscs = 2, FrontDiscMm = 298f, TankLitres = 20f,
                Seat = new Vector3(0, 0.79f, -0.22f), Grip = new Vector3(0.38f, 1.01f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.66f, 0.67f, 0.7f), Trim = new Color(0.1f, 0.1f, 0.11f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "not verified",
            WetMass = 209f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.46f, BrakeDecel = 9.5f,
            IdleRpm = 1300f, PeakRpm = 11500f, Redline = 13000f, LaunchRpm = 6300f,
            Torque = new (float, float)[] { (1300f, 33.6f), (4750f, 50f), (9500f, 61f), (10500f, 61f), (11500f, 58.6f), (13000f, 49.8f) },
            Gears = new[] { 2.846f, 1.947f, 1.556f, 1.333f, 1.19f, 1.083f }, Primary = 1.7f, FinalDrive = 3.5538f,
            RefZeroTo100 = 0f, RefTopKmh = 217f,
        },
        // ---- 124 ----
        // Yamaha FZS1000 Fazer (2001-05). docs/data/yamaha_fazer_r3_tmax_specs.json "FZS1000-2001" (FZS1000 Fazer).
        // 998 cc inline four, 143 PS at 10,000 rpm, 106 N·m at 7,500; 6 gears 2.846-1.083, primary 1.700, final 2.730; kerb 231 kg; wheelbase 1450 mm; rake 26.0°, trail 104 mm; 120/70ZR17 + 180/55ZR17.
        // https://en.wikipedia.org/wiki/Yamaha_FZ1
        // https://998cc.org/threads/the-gearing-thread.21459/latest
        // Assumed: 143 PS at 10,000 and 106 N·m at 7,500, the figures usually quoted for the FZS1000 (not in the dataset); redline 11,500; gear ratios borrowed from FZ6-2004 (spread only: the overall gearing is fitted below); primary 1.700 and final 2.730: the overall top gear fitted to 248 km/h at 105% of the peak-power rpm; seat 820 mm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.46 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1300, launch 5500; livery from "metallic blue with silver, black frame (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha FZS1000 Fazer (2001-05)",
            Brand = "Yamaha", Family = "Fazer",
            Blurb = "998 cc inline four, 143 PS, 231 kg, half fairing, upright",
            Engine = EngineLayout.Inline4Bike,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.InlineFour,
                Wheelbase = 1.45f, RakeDeg = 26f, Trail = 0.104f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "180/55ZR17", FrontTravel = 0.135f, RearTravel = 0.135f,
                FrontDiscs = 2, FrontDiscMm = 298f,
                Seat = new Vector3(0, 0.82f, -0.22f), Grip = new Vector3(0.38f, 1.04f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.08f, 0.22f, 0.7f), Trim = new Color(0.9f, 0.9f, 0.92f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 231f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.46f, BrakeDecel = 9.5f,
            IdleRpm = 1300f, PeakRpm = 10000f, Redline = 11500f, LaunchRpm = 5500f,
            Torque = new (float, float)[] { (1300f, 58.3f), (3750f, 86.9f), (7500f, 106f), (8750f, 105.3f), (10000f, 100.4f), (11500f, 85.4f) },
            Gears = new[] { 2.846f, 1.947f, 1.556f, 1.333f, 1.19f, 1.083f }, Primary = 1.7f, FinalDrive = 2.73f,
        },
        // ---- 125 ----
        // Yamaha FZ6 Fazer (FZ6-S) (2004-06). docs/data/yamaha_fazer_r3_tmax_specs.json "FZ6-2004" (FZ6-S (half-fairing Fazer)).
        // 600 cc inline four, 98 PS at 12,000 rpm, 63.1 N·m at 10,000; 6 gears 2.846-1.083, primary 1.955, final 2.875; kerb 208 kg; wheelbase 1440 mm; rake 25.0°, trail 97.5 mm; 120/70ZR17 + 180/55ZR17.
        // https://en.wikipedia.org/wiki/Yamaha_FZ6
        // https://www.gamestone.co.uk/steveszone/downloads/documents/yamaha_fz6_fazer_specs.txt
        // Assumed: redline 13,500; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.46 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1300, launch 6600; livery from "metallic silver-grey with dark grey frame (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha FZ6 Fazer (FZ6-S) (2004-06)",
            Brand = "Yamaha", Family = "Fazer",
            Blurb = "600 cc inline four, 98 PS, 208 kg, half fairing, upright",
            Engine = EngineLayout.Inline4Bike,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.InlineFour,
                Wheelbase = 1.44f, RakeDeg = 25f, Trail = 0.0975f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "180/55ZR17", FrontTravel = 0.13f, RearTravel = 0.13f,
                FrontDiscs = 2, FrontDiscMm = 298f, TankLitres = 19.4f, GroundClearance = 0.145f,
                Seat = new Vector3(0, 0.795f, -0.22f), Grip = new Vector3(0.38f, 1.015f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.66f, 0.67f, 0.7f), Trim = new Color(0.1f, 0.1f, 0.11f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 208f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.46f, BrakeDecel = 9.5f,
            IdleRpm = 1300f, PeakRpm = 12000f, Redline = 13500f, LaunchRpm = 6600f,
            Torque = new (float, float)[] { (1300f, 34.7f), (5000f, 51.7f), (10000f, 63.1f), (11000f, 61.4f), (12000f, 57.4f), (13500f, 48.8f) },
            Gears = new[] { 2.846f, 1.947f, 1.556f, 1.333f, 1.19f, 1.083f }, Primary = 1.955f, FinalDrive = 2.875f,
        },
        // ---- 126 ----
        // Yamaha FZ6 Fazer S2 (2007-10). docs/data/yamaha_fazer_r3_tmax_specs.json "FZ6-S2-2007" (FZ6 Fazer S2 (4-piston monoblock calipers, optional ABS)).
        // 600 cc inline four, 98 PS at 12,000 rpm, 63.1 N·m at 10,000; 6 gears 2.846-1.083, primary 1.955, final 2.875; kerb 208 kg; wheelbase 1440 mm; rake 25.0°, trail 97.5 mm; 120/70ZR17 + 180/55ZR17.
        // https://en.wikipedia.org/wiki/Yamaha_FZ6
        // https://www.gamestone.co.uk/steveszone/downloads/documents/yamaha_fz6_fazer_specs.txt
        // Assumed: redline 13,500; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.46 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1300, launch 6600; livery from "metallic blue/black with silver wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha FZ6 Fazer S2 (2007-10)",
            Brand = "Yamaha", Family = "Fazer",
            Blurb = "600 cc inline four, 98 PS, 208 kg, half fairing, upright",
            Engine = EngineLayout.Inline4Bike,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.InlineFour,
                Wheelbase = 1.44f, RakeDeg = 25f, Trail = 0.0975f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "180/55ZR17", FrontTravel = 0.13f, RearTravel = 0.13f,
                FrontDiscs = 2, FrontDiscMm = 298f, TankLitres = 19.4f, GroundClearance = 0.145f,
                Seat = new Vector3(0, 0.795f, -0.22f), Grip = new Vector3(0.38f, 1.015f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.08f, 0.22f, 0.7f), Trim = new Color(0.9f, 0.9f, 0.92f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 208f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.46f, BrakeDecel = 9.5f,
            IdleRpm = 1300f, PeakRpm = 12000f, Redline = 13500f, LaunchRpm = 6600f,
            Torque = new (float, float)[] { (1300f, 34.7f), (5000f, 51.7f), (10000f, 63.1f), (11000f, 61.4f), (12000f, 57.4f), (13500f, 48.8f) },
            Gears = new[] { 2.846f, 1.947f, 1.556f, 1.333f, 1.19f, 1.083f }, Primary = 1.955f, FinalDrive = 2.875f,
        },
        // ---- 127 ----
        // Yamaha FZ1 Fazer (FZ1-S) (2006-15). docs/data/yamaha_fazer_r3_tmax_specs.json "FZ1-FAZER-2006" (FZ1 Fazer (FZ1-S)).
        // 998 cc inline four, 150 PS at 11,000 rpm, 106 N·m at 8,000; 6 gears 2.846-1.083, primary 1.700, final 2.989; kerb 221 kg; wheelbase 1460 mm; rake 25.0°, trail 109 mm; 120/70ZR17 + 190/50ZR17.
        // Reference: 246 km/h (claimed (motorcyclespecs.co.za 246.1 km/h, test not named; Wikipedia 260 km/h)), 0-100 - s.
        // https://en.wikipedia.org/wiki/Yamaha_FZ1
        // https://www.motorcyclespecs.co.za/model/yamaha/yamaha_fz1%20fazer%2006.htm
        // https://www.ultimatespecs.com/motorcycles-specs/yamaha/yamaha-fz1-fazer-2010
        // Assumed: gear ratios borrowed from FZ6-2004 (spread only: the overall gearing is fitted below); primary 1.700 and final 2.989: the overall top gear fitted to 246 km/h at 105% of the peak-power rpm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.46 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1300, launch 6100; livery from "metallic blue-silver (Yamaha Blue) with black frame and wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha FZ1 Fazer (FZ1-S) (2006-15)",
            Brand = "Yamaha", Family = "Fazer",
            Blurb = "998 cc inline four, 150 PS, 221 kg, half fairing, upright",
            Engine = EngineLayout.Inline4Bike,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.InlineFour,
                Wheelbase = 1.46f, RakeDeg = 25f, Trail = 0.109f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "190/50ZR17", FrontTravel = 0.13f, RearTravel = 0.13f,
                FrontDiscs = 2, FrontDiscMm = 320f, TankLitres = 18f, GroundClearance = 0.135f,
                Seat = new Vector3(0, 0.815f, -0.22f), Grip = new Vector3(0.38f, 1.035f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.08f, 0.22f, 0.7f), Trim = new Color(0.9f, 0.9f, 0.92f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 221f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.46f, BrakeDecel = 9.5f,
            IdleRpm = 1300f, PeakRpm = 11000f, Redline = 12000f, LaunchRpm = 6100f,
            Torque = new (float, float)[] { (1300f, 58.3f), (4000f, 86.9f), (8000f, 106f), (9500f, 102.9f), (11000f, 95.8f), (12000f, 81.4f) },
            Gears = new[] { 2.846f, 1.947f, 1.556f, 1.333f, 1.19f, 1.083f }, Primary = 1.7f, FinalDrive = 2.989f,
            RefZeroTo100 = 0f, RefTopKmh = 246f,
        },
        // ---- 128 ----
        // Yamaha FZ8 / Fazer8 (2010-15). docs/data/yamaha_fazer_r3_tmax_specs.json "FZ8-2010" (FZ8-S Fazer8).
        // 779 cc inline four, 93 PS at 9,900 rpm, 71.0 N·m at 8,100; 6 gears 2.692-1.208, primary 1.700, final 2.754; kerb 215 kg; wheelbase 1460 mm; rake 25.0°, trail 109 mm; 120/70ZR17 + 180/55ZR17.
        // https://en.wikipedia.org/wiki/Yamaha_FZ8_and_FAZER8
        // web search result summary on Yamaha FZ8 gearbox (underlying page not opened)
        // Assumed: redline 11,400; primary 1.700 and final 2.754: the overall top gear fitted to 218 km/h at 105% of the peak-power rpm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.46 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1300, launch 5400; livery from "metallic grey/dark with black frame and wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha FZ8 / Fazer8 (2010-15)",
            Brand = "Yamaha", Family = "Fazer",
            Blurb = "779 cc inline four, 93 PS, 215 kg, half fairing, upright",
            Engine = EngineLayout.Inline4Bike,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.InlineFour,
                Wheelbase = 1.46f, RakeDeg = 25f, Trail = 0.109f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "180/55ZR17", FrontTravel = 0.135f, RearTravel = 0.135f,
                FrontDiscs = 2, FrontDiscMm = 310f, TankLitres = 17f,
                Seat = new Vector3(0, 0.815f, -0.22f), Grip = new Vector3(0.38f, 1.035f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.4f, 0.41f, 0.44f), Trim = new Color(0.1f, 0.1f, 0.11f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 215f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.46f, BrakeDecel = 9.5f,
            IdleRpm = 1300f, PeakRpm = 9900f, Redline = 11400f, LaunchRpm = 5400f,
            Torque = new (float, float)[] { (1300f, 39.1f), (4050f, 58.2f), (8100f, 71f), (9000f, 69.8f), (9900f, 65.9f), (11400f, 56f) },
            Gears = new[] { 2.692f, 2.063f, 1.762f, 1.522f, 1.35f, 1.208f }, Primary = 1.7f, FinalDrive = 2.7536f,
        },
        // ---- 129 ----
        // Yamaha YZF-R3 (2016). docs/data/yamaha_fazer_r3_tmax_specs.json "YZFR3-2016" (YZF-R3 (321 cc, ABS)).
        // 321 cc 180° parallel twin, 42 PS at 10,750 rpm, 30 N·m at 9,000; 6 gears 2.5-0.8, primary 3.043, final 3.071; kerb 169 kg; wheelbase 1380 mm; rake 25.0°, trail 95 mm; 110/70-17 + 140/70-17.
        // https://global.yamaha-motor.com/jp/news/2015/0223/yzf-r3.html
        // https://en.wikipedia.org/wiki/Yamaha_YZF-R3
        // Assumed: redline 11,550; the sport values (CG 0.6 m, 49% rear, CdA 0.36 m², grip 1.1, 50° lean, brakes 9.8 m/s², riding position), the torque curve between the peaks, idle 1200, launch 5900; livery from "Yamaha blue fairing with white/silver accents, black frame, blue wheels".
        new MotorbikeSpec
        {
            Label = "Yamaha YZF-R3 (2016)",
            Brand = "Yamaha", Family = "YZF-R3",
            Blurb = "321 cc 180° parallel twin, 42 PS, 169 kg, clip-ons and a full fairing",
            Engine = EngineLayout.ParallelTwin180,
            Look = new MotoLook
            {
                Style = MotoStyle.Sport, EngineShape = MotoEngineShape.ParallelTwin,
                Wheelbase = 1.38f, RakeDeg = 25f, Trail = 0.095f, ForkLength = 0.62f,
                FrontTyre = "110/70-17", RearTyre = "140/70-17", FrontTravel = 0.13f, RearTravel = 0.13f,
                FrontDiscs = 1, FrontDiscMm = 298f, TankLitres = 14f, GroundClearance = 0.16f,
                Seat = new Vector3(0, 0.78f, -0.24f), Grip = new Vector3(0.32f, 0.76f, 0.36f), Peg = new Vector3(0.17f, 0.36f, -0.18f),
                Paint = new Color(0.08f, 0.22f, 0.7f), Trim = new Color(0.9f, 0.9f, 0.92f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.08f, 0.22f, 0.7f),
            },
            Colours = "Deep Purplish Blue Metallic C; Black Metallic X; Vivid Red Cocktail 1",
            WetMass = 169f, CgHeight = 0.6f, RearShare = 0.49f, Grip = 1.1f, MaxLean = Mathf.DegToRad(50f),
            DragArea = 0.36f, BrakeDecel = 9.8f,
            IdleRpm = 1200f, PeakRpm = 10750f, Redline = 11550f, LaunchRpm = 5900f,
            Torque = new (float, float)[] { (1200f, 16.5f), (4500f, 24.6f), (9000f, 30f), (9875f, 29.3f), (10750f, 27.4f), (11550f, 23.3f) },
            Gears = new[] { 2.5f, 1.823f, 1.347f, 1.086f, 0.92f, 0.8f }, Primary = 3.043f, FinalDrive = 3.071f,
        },
        // ---- 130 ----
        // Yamaha TMAX 500 (XP500) (2001-07). docs/data/yamaha_fazer_r3_tmax_specs.json "TMAX500-2001" (TMAX 500 first generation).
        // 499 cc 360° parallel twin, 38 PS at 7,500 rpm, 45 N·m at 4,500; CVT 2.025-0.728, primary 2.659, final 2.262; kerb 225 kg; wheelbase 1575 mm; rake 28.0°, trail 95 mm; 120/70R14 + 160/60R15.
        // https://global.yamaha-motor.com/jp/news/2004/0714/tmax.html
        // https://global.yamaha-motor.com/jp/news/2005/0818/tmax.html
        // https://en.wikipedia.org/wiki/Yamaha_TMAX
        // Assumed: redline 8,000; seat 800 mm; the scooter values (CG 0.58 m, 55% rear, CdA 0.55 m², grip 1.0, 43° lean, brakes 8.5 m/s², riding position), the torque curve between the peaks, idle 1200, launch 4100; livery from "metallic silver-grey with black seat, black engine and wheels (unverified, original launch colour)".
        new MotorbikeSpec
        {
            Label = "Yamaha TMAX 500 (XP500) (2001-07)",
            Brand = "Yamaha", Family = "TMAX",
            Blurb = "499 cc 360° parallel twin, 38 PS, 225 kg, twist and go: CVT automatic",
            Engine = EngineLayout.ParallelTwin360,
            Look = new MotoLook
            {
                Style = MotoStyle.Scooter, EngineShape = MotoEngineShape.ParallelTwin,
                Wheelbase = 1.575f, RakeDeg = 28f, Trail = 0.095f, ForkLength = 0.55f,
                FrontTyre = "120/70R14", RearTyre = "160/60R15", FrontTravel = 0.12f, RearTravel = 0.12f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 14f,
                Seat = new Vector3(0, 0.8f, -0.25f), Grip = new Vector3(0.36f, 1.05f, 0.32f), Peg = new Vector3(0.17f, 0.3f, 0.22f),
                Paint = new Color(0.66f, 0.67f, 0.7f), Trim = new Color(0.1f, 0.1f, 0.11f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "Deep Red Metallic K; Black Metallic X; Dark Purplish Blue Metallic L",
            WetMass = 225f, CgHeight = 0.58f, RearShare = 0.55f, Grip = 1f, MaxLean = Mathf.DegToRad(43f),
            DragArea = 0.55f, BrakeDecel = 8.5f,
            IdleRpm = 1200f, PeakRpm = 7500f, Redline = 8000f, LaunchRpm = 4100f,
            Torque = new (float, float)[] { (1200f, 24.8f), (2250f, 36.9f), (4500f, 45f), (6000f, 41.1f), (7500f, 35.6f), (8000f, 30.2f) },
            Gears = new[] { 2.025f }, Primary = 2.659f, FinalDrive = 2.262f,
            Cvt = true, CvtHigh = 0.728f, CvtRpm = 7500f,
        },
        // ---- 131 ----
        // Yamaha TMAX 500 (XP500) (2008-11). docs/data/yamaha_fazer_r3_tmax_specs.json "TMAX500-2008" (TMAX 500 second generation (aluminium frame)).
        // 499 cc 360° parallel twin, 44 PS at 7,500 rpm, 45 N·m at 6,500; CVT 2.025-0.728, primary 2.659, final 2.262; kerb 222 kg; wheelbase 1580 mm; rake 25.0°, trail 92 mm; 120/70R15 + 160/60R15.
        // https://global.yamaha-motor.com/jp/news/2008/0604/tmax.html
        // https://global.yamaha-motor.com/jp/news/2010/0727/tmax.html
        // https://en.wikipedia.org/wiki/Yamaha_TMAX
        // Assumed: redline 8,000; seat 800 mm; the scooter values (CG 0.58 m, 55% rear, CdA 0.55 m², grip 1.0, 43° lean, brakes 8.5 m/s², riding position), the torque curve between the peaks, idle 1200, launch 4100; livery from "metallic black with silver-grey frame covers and black wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha TMAX 500 (XP500) (2008-11)",
            Brand = "Yamaha", Family = "TMAX",
            Blurb = "499 cc 360° parallel twin, 44 PS, 222 kg, twist and go: CVT automatic",
            Engine = EngineLayout.ParallelTwin360,
            Look = new MotoLook
            {
                Style = MotoStyle.Scooter, EngineShape = MotoEngineShape.ParallelTwin,
                Wheelbase = 1.58f, RakeDeg = 25f, Trail = 0.092f, ForkLength = 0.55f,
                FrontTyre = "120/70R15", RearTyre = "160/60R15", FrontTravel = 0.12f, RearTravel = 0.12f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 15f,
                Seat = new Vector3(0, 0.8f, -0.25f), Grip = new Vector3(0.36f, 1.05f, 0.32f), Peg = new Vector3(0.17f, 0.3f, 0.22f),
                Paint = new Color(0.08f, 0.08f, 0.09f), Trim = new Color(0.55f, 0.56f, 0.6f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "Reddish Yellow Cocktail 1; Dark Purplish Blue Metallic X; Black Metallic X; High-Tech Silver (2010)",
            WetMass = 222f, CgHeight = 0.58f, RearShare = 0.55f, Grip = 1f, MaxLean = Mathf.DegToRad(43f),
            DragArea = 0.55f, BrakeDecel = 8.5f,
            IdleRpm = 1200f, PeakRpm = 7500f, Redline = 8000f, LaunchRpm = 4100f,
            Torque = new (float, float)[] { (1200f, 24.8f), (3250f, 36.9f), (6500f, 45f), (7000f, 43.7f), (7500f, 40.7f), (8000f, 34.6f) },
            Gears = new[] { 2.025f }, Primary = 2.659f, FinalDrive = 2.262f,
            Cvt = true, CvtHigh = 0.728f, CvtRpm = 7500f,
        },
        // ---- 132 ----
        // Yamaha TMAX 530 (XP530) (2012-16). docs/data/yamaha_fazer_r3_tmax_specs.json "TMAX530-2012" (TMAX 530 (ABS optional)).
        // 530 cc 360° parallel twin, 46 PS at 6,750 rpm, 52.3 N·m at 5,250; CVT 2.041-0.758, primary 1.000, final 6.034; kerb 217 kg; wheelbase 1580 mm; rake 25.0°, trail 92 mm; 120/70R15 + 160/60R15.
        // https://global.yamaha-motor.com/jp/news/2013/0515/tmax.html
        // https://en.wikipedia.org/wiki/Yamaha_TMAX
        // Assumed: redline 7,250; seat 800 mm; the scooter values (CG 0.58 m, 55% rear, CdA 0.55 m², grip 1.0, 43° lean, brakes 8.5 m/s², riding position), the torque curve between the peaks, idle 1200, launch 3700; livery from "black metallic with matt grey/silver trim and black wheels".
        new MotorbikeSpec
        {
            Label = "Yamaha TMAX 530 (XP530) (2012-16)",
            Brand = "Yamaha", Family = "TMAX",
            Blurb = "530 cc 360° parallel twin, 46 PS, 217 kg, twist and go: CVT automatic",
            Engine = EngineLayout.ParallelTwin360,
            Look = new MotoLook
            {
                Style = MotoStyle.Scooter, EngineShape = MotoEngineShape.ParallelTwin,
                Wheelbase = 1.58f, RakeDeg = 25f, Trail = 0.092f, ForkLength = 0.55f,
                FrontTyre = "120/70R15", RearTyre = "160/60R15", FrontTravel = 0.12f, RearTravel = 0.12f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 15f,
                Seat = new Vector3(0, 0.8f, -0.25f), Grip = new Vector3(0.36f, 1.05f, 0.32f), Peg = new Vector3(0.17f, 0.3f, 0.22f),
                Paint = new Color(0.08f, 0.08f, 0.09f), Trim = new Color(0.55f, 0.56f, 0.6f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "Black Metallic M; Bluish White Cocktail 1; Matt Dark Gray Metallic 1 (ABS); Matt Black 2 (Black MAX)",
            WetMass = 217f, CgHeight = 0.58f, RearShare = 0.55f, Grip = 1f, MaxLean = Mathf.DegToRad(43f),
            DragArea = 0.55f, BrakeDecel = 8.5f,
            IdleRpm = 1200f, PeakRpm = 6750f, Redline = 7250f, LaunchRpm = 3700f,
            Torque = new (float, float)[] { (1200f, 28.8f), (2625f, 42.9f), (5250f, 52.3f), (6000f, 51.3f), (6750f, 48.4f), (7250f, 41.1f) },
            Gears = new[] { 2.041f }, Primary = 1f, FinalDrive = 6.034f,
            Cvt = true, CvtHigh = 0.758f, CvtRpm = 6750f,
        },
        // ---- 133 ----
        // Yamaha TMAX 530 SX / DX (XP530-A) (2017-19). docs/data/yamaha_fazer_r3_tmax_specs.json "TMAX530-SX-DX-2017" (TMAX 530 SX (standard) and DX (premium)).
        // 530 cc 360° parallel twin, 46 PS at 6,750 rpm, 53.0 N·m at 5,250; CVT 2.041-0.758, primary 1.000, final 6.034; kerb 216 kg; wheelbase 1580 mm; rake 26.0°, trail 98 mm; 120/70R15 + 160/60R15.
        // https://en.wikipedia.org/wiki/Yamaha_TMAX
        // https://global.yamaha-motor.com/jp/news/2013/0515/tmax.html
        // Assumed: wheelbase 1,580 mm as the 2012 TMAX 530 (same frame); redline 7,250; secondary reduction 6.034 as the 2012 TMAX 530 (same engine); seat 800 mm; the scooter values (CG 0.58 m, 55% rear, CdA 0.55 m², grip 1.0, 43° lean, brakes 8.5 m/s², riding position), the torque curve between the peaks, idle 1200, launch 3700; livery from "DX: matt/metallic grey with dark frame and black wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha TMAX 530 SX / DX (XP530-A) (2017-19)",
            Brand = "Yamaha", Family = "TMAX",
            Blurb = "530 cc 360° parallel twin, 46 PS, 216 kg, twist and go: CVT automatic",
            Engine = EngineLayout.ParallelTwin360,
            Look = new MotoLook
            {
                Style = MotoStyle.Scooter, EngineShape = MotoEngineShape.ParallelTwin,
                Wheelbase = 1.58f, RakeDeg = 26f, Trail = 0.098f, ForkLength = 0.55f,
                FrontTyre = "120/70R15", RearTyre = "160/60R15", FrontTravel = 0.12f, RearTravel = 0.12f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 15f,
                Seat = new Vector3(0, 0.8f, -0.25f), Grip = new Vector3(0.36f, 1.05f, 0.32f), Peg = new Vector3(0.17f, 0.3f, 0.22f),
                Paint = new Color(0.4f, 0.41f, 0.44f), Trim = new Color(0.1f, 0.1f, 0.11f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 216f, CgHeight = 0.58f, RearShare = 0.55f, Grip = 1f, MaxLean = Mathf.DegToRad(43f),
            DragArea = 0.55f, BrakeDecel = 8.5f,
            IdleRpm = 1200f, PeakRpm = 6750f, Redline = 7250f, LaunchRpm = 3700f,
            Torque = new (float, float)[] { (1200f, 29.2f), (2625f, 43.5f), (5250f, 53f), (6000f, 51.4f), (6750f, 47.9f), (7250f, 40.7f) },
            Gears = new[] { 2.041f }, Primary = 1f, FinalDrive = 6.034f,
            Cvt = true, CvtHigh = 0.758f, CvtRpm = 6750f,
        },
        // ---- 134 ----
        // Yamaha TMAX 560 (2020-21). docs/data/yamaha_fazer_r3_tmax_specs.json "TMAX560-2020" (TMAX 560 and TMAX 560 Tech MAX).
        // 561 cc 360° parallel twin, 48 PS at 7,500 rpm, 56 N·m at 5,250; CVT 2.041-0.758, primary 1.000, final 5.771; kerb 218 kg; wheelbase 1575 mm; rake 26.0°, trail 98 mm; 120/70R15 + 160/60R15.
        // https://motor-fan.jp/article/781416/2/
        // https://bikebros.co.jp/catalog/2/999_94/
        // https://moto.motorionline.com/en/nuovi-yamaha-tmax-560-tmax-tech-max-caratteristiche-colorazioni-arrivo-prezzi/
        // Assumed: redline 8,000; the scooter values (CG 0.58 m, 55% rear, CdA 0.55 m², grip 1.0, 43° lean, brakes 8.5 m/s², riding position), the torque curve between the peaks, idle 1200, launch 4100; livery from "matt dark grey metallic with black frame and wheels (JP colour; unverified for EU)".
        new MotorbikeSpec
        {
            Label = "Yamaha TMAX 560 (2020-21)",
            Brand = "Yamaha", Family = "TMAX",
            Blurb = "561 cc 360° parallel twin, 48 PS, 218 kg, twist and go: CVT automatic",
            Engine = EngineLayout.ParallelTwin360,
            Look = new MotoLook
            {
                Style = MotoStyle.Scooter, EngineShape = MotoEngineShape.ParallelTwin,
                Wheelbase = 1.575f, RakeDeg = 26f, Trail = 0.098f, ForkLength = 0.55f,
                FrontTyre = "120/70R15", RearTyre = "160/60R15", FrontTravel = 0.12f, RearTravel = 0.12f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 15f,
                Seat = new Vector3(0, 0.8f, -0.25f), Grip = new Vector3(0.36f, 1.05f, 0.32f), Peg = new Vector3(0.17f, 0.3f, 0.22f),
                Paint = new Color(0.4f, 0.41f, 0.44f), Trim = new Color(0.1f, 0.1f, 0.11f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "Matte Dark Grey Metallic D (JP)",
            WetMass = 218f, CgHeight = 0.58f, RearShare = 0.55f, Grip = 1f, MaxLean = Mathf.DegToRad(43f),
            DragArea = 0.55f, BrakeDecel = 8.5f,
            IdleRpm = 1200f, PeakRpm = 7500f, Redline = 8000f, LaunchRpm = 4100f,
            Torque = new (float, float)[] { (1200f, 30.8f), (2625f, 45.9f), (5250f, 56f), (6375f, 51.5f), (7500f, 45f), (8000f, 38.2f) },
            Gears = new[] { 2.041f }, Primary = 1f, FinalDrive = 5.771f,
            Cvt = true, CvtHigh = 0.758f, CvtRpm = 7500f,
        },
        // ---- 135 ----
        // Yamaha TMAX 560 (2022+). docs/data/yamaha_fazer_r3_tmax_specs.json "TMAX560-2022" (TMAX 560 / Tech MAX (2022 update)).
        // 561 cc 360° parallel twin, 48 PS at 7,500 rpm, 56 N·m at 5,250; CVT 2.041-0.758, primary 1.000, final 5.771; kerb 218 kg; wheelbase 1575 mm; rake 26.0°, trail 98 mm; 120/70R15 + 160/60R15.
        // https://motor-fan.jp/article/781416/2/
        // https://bikebros.co.jp/catalog/2/999_94/
        // https://moto.motorionline.com/en/nuovi-yamaha-tmax-560-tmax-tech-max-caratteristiche-colorazioni-arrivo-prezzi/
        // Assumed: redline 8,000; the scooter values (CG 0.58 m, 55% rear, CdA 0.55 m², grip 1.0, 43° lean, brakes 8.5 m/s², riding position), the torque curve between the peaks, idle 1200, launch 4100; livery from "matt grey (Tech MAX) with dark frame, black wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha TMAX 560 (2022+)",
            Brand = "Yamaha", Family = "TMAX",
            Blurb = "561 cc 360° parallel twin, 48 PS, 218 kg, twist and go: CVT automatic",
            Engine = EngineLayout.ParallelTwin360,
            Look = new MotoLook
            {
                Style = MotoStyle.Scooter, EngineShape = MotoEngineShape.ParallelTwin,
                Wheelbase = 1.575f, RakeDeg = 26f, Trail = 0.098f, ForkLength = 0.55f,
                FrontTyre = "120/70R15", RearTyre = "160/60R15", FrontTravel = 0.12f, RearTravel = 0.12f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 15f,
                Seat = new Vector3(0, 0.8f, -0.25f), Grip = new Vector3(0.36f, 1.05f, 0.32f), Peg = new Vector3(0.17f, 0.3f, 0.22f),
                Paint = new Color(0.4f, 0.41f, 0.44f), Trim = new Color(0.1f, 0.1f, 0.11f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 218f, CgHeight = 0.58f, RearShare = 0.55f, Grip = 1f, MaxLean = Mathf.DegToRad(43f),
            DragArea = 0.55f, BrakeDecel = 8.5f,
            IdleRpm = 1200f, PeakRpm = 7500f, Redline = 8000f, LaunchRpm = 4100f,
            Torque = new (float, float)[] { (1200f, 30.8f), (2625f, 45.9f), (5250f, 56f), (6375f, 51.5f), (7500f, 45f), (8000f, 38.2f) },
            Gears = new[] { 2.041f }, Primary = 1f, FinalDrive = 5.771f,
            Cvt = true, CvtHigh = 0.758f, CvtRpm = 7500f,
        },
        // ---- 136 ----
        // Yamaha XT1200Z Super Ténéré (2010-13). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "XT1200Z-2010" (XT1200Z (2010-2013)).
        // 1199 cc 270° parallel twin, 110 PS at 7,250 rpm, 114.1 N·m at 6,000; 6 gears 2.769-0.929, primary 1.466, final 2.987; kerb 261 kg; wheelbase 1540 mm; rake 28.0°, trail 125 mm; 110/80R19 + 150/70R17.
        // Reference: 210 km/h (claimed (motorradundreisen database)), 0-100 3.7 s.
        // https://global.yamaha-motor.com/jp/news/2010/0225/supertenere.html
        // https://www.motorradonline.de/test/top-test-yamaha-xt-1200-z-super-tenere.308410.html
        // https://www.lerepairedesmotards.com/technique/fiches/tech-yamaha-xtz-1200-super-tenere.php
        // Assumed: redline 8,050; the adventure values (CG 0.74 m, 50% rear, CdA 0.55 m², grip 1.0, 45° lean, brakes 9.0 m/s², riding position), the torque curve between the peaks, idle 1200, launch 4000; livery from "white with blue-grey frame accents, black engine, silver wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha XT1200Z Super Ténéré (2010-13)",
            Brand = "Yamaha", Family = "Super Ténéré",
            Blurb = "1199 cc 270° parallel twin, 110 PS, 261 kg, adventure tyres: grips on gravel and grass",
            Engine = EngineLayout.ParallelTwin270,
            Look = new MotoLook
            {
                Style = MotoStyle.Adventure, EngineShape = MotoEngineShape.ParallelTwin, Spoked = true,
                Wheelbase = 1.54f, RakeDeg = 28f, Trail = 0.125f, ForkLength = 0.84f,
                FrontTyre = "110/80R19", RearTyre = "150/70R17", FrontTravel = 0.19f, RearTravel = 0.19f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 23f,
                Seat = new Vector3(0, 0.845f, -0.2f), Grip = new Vector3(0.43f, 1.145f, 0.3f), Peg = new Vector3(0.19f, 0.42f, -0.05f),
                Paint = new Color(0.92f, 0.92f, 0.9f), Trim = new Color(0.08f, 0.17f, 0.55f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 261f, CgHeight = 0.74f, RearShare = 0.5f, Grip = 1f, OffroadTyre = 0.3f, MaxLean = Mathf.DegToRad(45f),
            DragArea = 0.55f, BrakeDecel = 9f,
            IdleRpm = 1200f, PeakRpm = 7250f, Redline = 8050f, LaunchRpm = 4000f,
            Torque = new (float, float)[] { (1200f, 62.8f), (3000f, 93.6f), (6000f, 114.1f), (6625f, 112.5f), (7250f, 106.6f), (8050f, 90.6f) },
            Gears = new[] { 2.769f, 2.063f, 1.571f, 1.25f, 1.042f, 0.929f }, Primary = 1.466f, FinalDrive = 2.987f,
            RefZeroTo100 = 3.7f, RefTopKmh = 210f,
        },
        // ---- 137 ----
        // Yamaha XT1200Z Super Ténéré (2014-21). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "XT1200Z-2014" (XT1200Z standard (2014-2021)).
        // 1199 cc 270° parallel twin, 112 PS at 7,250 rpm, 117 N·m at 6,000; 6 gears 2.769-0.929, primary 1.466, final 2.987; kerb 257 kg; wheelbase 1540 mm; rake 28.0°, trail 126 mm; 110/80R19 + 150/70R17.
        // Reference: 210 km/h (claimed (motorradundreisen database)), 0-100 - s.
        // https://bikebros.co.jp/catalog/2/86_12/
        // https://bikebros.co.jp/catalog/2/86_20/
        // https://www.motorradundreisen.de/motorraddatenbank/yamaha/xt1200ze-26312.html
        // Assumed: redline 8,050; the adventure values (CG 0.74 m, 50% rear, CdA 0.55 m², grip 1.0, 45° lean, brakes 9.0 m/s², riding position), the torque curve between the peaks, idle 1200, launch 4000; livery from "Ceramic Ice pale grey-white with black frame and black wheels".
        new MotorbikeSpec
        {
            Label = "Yamaha XT1200Z Super Ténéré (2014-21)",
            Brand = "Yamaha", Family = "Super Ténéré",
            Blurb = "1199 cc 270° parallel twin, 112 PS, 257 kg, adventure tyres: grips on gravel and grass",
            Engine = EngineLayout.ParallelTwin270,
            Look = new MotoLook
            {
                Style = MotoStyle.Adventure, EngineShape = MotoEngineShape.ParallelTwin, Spoked = true,
                Wheelbase = 1.54f, RakeDeg = 28f, Trail = 0.126f, ForkLength = 0.84f,
                FrontTyre = "110/80R19", RearTyre = "150/70R17", FrontTravel = 0.19f, RearTravel = 0.19f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 23f,
                Seat = new Vector3(0, 0.845f, -0.2f), Grip = new Vector3(0.43f, 1.145f, 0.3f), Peg = new Vector3(0.19f, 0.42f, -0.05f),
                Paint = new Color(0.4f, 0.41f, 0.44f), Trim = new Color(0.1f, 0.1f, 0.11f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "Ceramic Ice; Tech Black",
            WetMass = 257f, CgHeight = 0.74f, RearShare = 0.5f, Grip = 1f, OffroadTyre = 0.3f, MaxLean = Mathf.DegToRad(45f),
            DragArea = 0.55f, BrakeDecel = 9f,
            IdleRpm = 1200f, PeakRpm = 7250f, Redline = 8050f, LaunchRpm = 4000f,
            Torque = new (float, float)[] { (1200f, 64.4f), (3000f, 95.9f), (6000f, 117f), (6625f, 115f), (7250f, 108.5f), (8050f, 92.2f) },
            Gears = new[] { 2.769f, 2.063f, 1.571f, 1.25f, 1.042f, 0.929f }, Primary = 1.466f, FinalDrive = 2.987f,
            RefZeroTo100 = 0f, RefTopKmh = 210f,
        },
        // ---- 138 ----
        // Yamaha XT1200ZE Super Ténéré (2014-21). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "XT1200ZE-2014" (XT1200ZE electronic suspension (2014-2021)).
        // 1199 cc 270° parallel twin, 112 PS at 7,250 rpm, 117 N·m at 6,000; 6 gears 2.769-0.929, primary 1.466, final 2.987; kerb 266 kg; wheelbase 1540 mm; rake 28.0°, trail 126 mm; 110/80R19 + 150/70R17.
        // Reference: 210 km/h (claimed (motorradundreisen database)), 0-100 - s.
        // https://bikebros.co.jp/catalog/2/86_20/
        // https://www.motorradundreisen.de/motorraddatenbank/yamaha/xt1200ze-26312.html
        // Assumed: redline 8,050; the adventure values (CG 0.74 m, 50% rear, CdA 0.55 m², grip 1.0, 45° lean, brakes 9.0 m/s², riding position), the torque curve between the peaks, idle 1200, launch 4000; livery from "Tech black with silver frame details and black wheels (Ceramic Ice alternate)".
        new MotorbikeSpec
        {
            Label = "Yamaha XT1200ZE Super Ténéré (2014-21)",
            Brand = "Yamaha", Family = "Super Ténéré",
            Blurb = "1199 cc 270° parallel twin, 112 PS, 266 kg, adventure tyres: grips on gravel and grass",
            Engine = EngineLayout.ParallelTwin270,
            Look = new MotoLook
            {
                Style = MotoStyle.Adventure, EngineShape = MotoEngineShape.ParallelTwin, Spoked = true,
                Wheelbase = 1.54f, RakeDeg = 28f, Trail = 0.126f, ForkLength = 0.84f,
                FrontTyre = "110/80R19", RearTyre = "150/70R17", FrontTravel = 0.19f, RearTravel = 0.19f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 23f,
                Seat = new Vector3(0, 0.845f, -0.2f), Grip = new Vector3(0.43f, 1.145f, 0.3f), Peg = new Vector3(0.19f, 0.42f, -0.05f),
                Paint = new Color(0.08f, 0.08f, 0.09f), Trim = new Color(0.55f, 0.56f, 0.6f), Frame = new Color(0.66f, 0.67f, 0.7f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "Ceramic Ice; Tech Black",
            WetMass = 266f, CgHeight = 0.74f, RearShare = 0.5f, Grip = 1f, OffroadTyre = 0.3f, MaxLean = Mathf.DegToRad(45f),
            DragArea = 0.55f, BrakeDecel = 9f,
            IdleRpm = 1200f, PeakRpm = 7250f, Redline = 8050f, LaunchRpm = 4000f,
            Torque = new (float, float)[] { (1200f, 64.4f), (3000f, 95.9f), (6000f, 117f), (6625f, 115f), (7250f, 108.5f), (8050f, 92.2f) },
            Gears = new[] { 2.769f, 2.063f, 1.571f, 1.25f, 1.042f, 0.929f }, Primary = 1.466f, FinalDrive = 2.987f,
            RefZeroTo100 = 0f, RefTopKmh = 210f,
        },
        // ---- 139 ----
        // Yamaha MT-09 Tracer (2015-17). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "MT09TRACER-2015" (MT-09 Tracer ABS (2015-2017)).
        // 847 cc CP3 triple, 115 PS at 10,000 rpm, 87.5 N·m at 8,500; 6 gears 2.666-1.037, primary 1.680, final 2.812; kerb 210 kg; wheelbase 1440 mm; rake 24.0°, trail 100 mm; 120/70ZR17 + 180/55ZR17.
        // https://bikebros.co.jp/catalog/2/43_7/
        // https://en.wikipedia.org/wiki/Yamaha_Tracer_900
        // Assumed: CdA 0.59 m² for the Tracer 900 / 9, fitted to the Tracer 9 GT's measured 214 km/h (the generic 0.46 gave 233); redline 11,000; seat 820 mm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.59 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1250, launch 5500; livery from "Yamaha blue with white flanks, black frame, blue wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha MT-09 Tracer (2015-17)",
            Brand = "Yamaha", Family = "Tracer",
            Blurb = "847 cc CP3 triple, 115 PS, 210 kg, half fairing, upright",
            Engine = EngineLayout.Triple,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.Triple,
                Wheelbase = 1.44f, RakeDeg = 24f, Trail = 0.1f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "180/55ZR17", FrontTravel = 0.135f, RearTravel = 0.135f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 18f,
                Seat = new Vector3(0, 0.82f, -0.22f), Grip = new Vector3(0.38f, 1.04f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.08f, 0.22f, 0.7f), Trim = new Color(0.9f, 0.9f, 0.92f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.08f, 0.22f, 0.7f),
            },
            Colours = "",
            WetMass = 210f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.59f, BrakeDecel = 9.5f,
            IdleRpm = 1250f, PeakRpm = 10000f, Redline = 11000f, LaunchRpm = 5500f,
            Torque = new (float, float)[] { (1250f, 48.1f), (4250f, 71.8f), (8500f, 87.5f), (9250f, 85.8f), (10000f, 80.8f), (11000f, 68.7f) },
            Gears = new[] { 2.666f, 2f, 1.619f, 1.38f, 1.19f, 1.037f }, Primary = 1.68f, FinalDrive = 2.812f,
        },
        // ---- 140 ----
        // Yamaha Tracer 900 (2018-20). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "TRACER900-2018" (Tracer 900 (2018-2020)).
        // 847 cc CP3 triple, 115 PS at 10,000 rpm, 87.5 N·m at 8,500; 6 gears 2.666-1.037, primary 1.680, final 2.812; kerb 210 kg; wheelbase 1440 mm; rake 24.0°, trail 100 mm; 120/70ZR17 + 180/55ZR17.
        // https://bikebros.co.jp/catalog/2/999_125/13734/
        // https://global.yamaha-motor.com/jp/news/2018/0313/tracer900.html
        // https://en.wikipedia.org/wiki/Yamaha_Tracer_900
        // Assumed: kerb 210 kg as the MT-09 Tracer it replaced; CdA 0.59 m² for the Tracer 900 / 9, fitted to the Tracer 9 GT's measured 214 km/h (the generic 0.46 gave 233); redline 11,000; seat 820 mm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.59 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1250, launch 5500; livery from "matt grey with black frame and black wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha Tracer 900 (2018-20)",
            Brand = "Yamaha", Family = "Tracer",
            Blurb = "847 cc CP3 triple, 115 PS, 210 kg, half fairing, upright",
            Engine = EngineLayout.Triple,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.Triple,
                Wheelbase = 1.44f, RakeDeg = 24f, Trail = 0.1f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "180/55ZR17", FrontTravel = 0.135f, RearTravel = 0.135f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 18f,
                Seat = new Vector3(0, 0.82f, -0.22f), Grip = new Vector3(0.38f, 1.04f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.4f, 0.41f, 0.44f), Trim = new Color(0.1f, 0.1f, 0.11f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 210f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.59f, BrakeDecel = 9.5f,
            IdleRpm = 1250f, PeakRpm = 10000f, Redline = 11000f, LaunchRpm = 5500f,
            Torque = new (float, float)[] { (1250f, 48.1f), (4250f, 71.8f), (8500f, 87.5f), (9250f, 85.8f), (10000f, 80.8f), (11000f, 68.7f) },
            Gears = new[] { 2.666f, 2f, 1.619f, 1.38f, 1.19f, 1.037f }, Primary = 1.68f, FinalDrive = 2.812f,
        },
        // ---- 141 ----
        // Yamaha Tracer 900 GT (2018-20). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "TRACER900GT-2018" (Tracer 900 GT (2018-2020)).
        // 847 cc CP3 triple, 115 PS at 10,000 rpm, 87.5 N·m at 8,500; 6 gears 2.666-1.037, primary 1.680, final 2.812; kerb 215 kg; wheelbase 1500 mm; rake 24.0°, trail 100 mm; 120/70ZR17 + 180/55ZR17.
        // https://bikebros.co.jp/catalog/2/999_125/13734/
        // https://global.yamaha-motor.com/jp/news/2018/0313/tracer900.html
        // Assumed: CdA 0.59 m² for the Tracer 900 / 9, fitted to the Tracer 9 GT's measured 214 km/h (the generic 0.46 gave 233); redline 11,000; seat 820 mm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.59 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1250, launch 5500; livery from "Yamaha blue with grey fairing, black frame and black wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha Tracer 900 GT (2018-20)",
            Brand = "Yamaha", Family = "Tracer",
            Blurb = "847 cc CP3 triple, 115 PS, 215 kg, half fairing, upright",
            Engine = EngineLayout.Triple,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.Triple,
                Wheelbase = 1.5f, RakeDeg = 24f, Trail = 0.1f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "180/55ZR17", FrontTravel = 0.135f, RearTravel = 0.135f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 18f,
                Seat = new Vector3(0, 0.82f, -0.22f), Grip = new Vector3(0.38f, 1.04f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.08f, 0.22f, 0.7f), Trim = new Color(0.9f, 0.9f, 0.92f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 215f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.59f, BrakeDecel = 9.5f,
            IdleRpm = 1250f, PeakRpm = 10000f, Redline = 11000f, LaunchRpm = 5500f,
            Torque = new (float, float)[] { (1250f, 48.1f), (4250f, 71.8f), (8500f, 87.5f), (9250f, 85.8f), (10000f, 80.8f), (11000f, 68.7f) },
            Gears = new[] { 2.666f, 2f, 1.619f, 1.38f, 1.19f, 1.037f }, Primary = 1.68f, FinalDrive = 2.812f,
        },
        // ---- 142 ----
        // Yamaha Tracer 700 (2016-19). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "TRACER700-2016" (Tracer 700 (2016-2019)).
        // 689 cc 270° parallel twin, 75 PS at 9,000 rpm, 68 N·m at 6,500; 6 gears 2.846-0.964, primary 1.925, final 2.812; kerb 196 kg; wheelbase 1460 mm; rake 24.0°, trail 90 mm; 120/70ZR17 + 180/55ZR17.
        // https://en.wikipedia.org/wiki/Yamaha_Tracer_700
        // https://bikebros.co.jp/catalog/2/999_16/
        // Assumed: redline 9,800; primary 77/40 = 1.925 as the MT-07 (same CP2 engine; not in the dataset); seat 820 mm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.46 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1200, launch 5000; livery from "Yamaha blue with white fairing flanks, black frame, blue wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha Tracer 700 (2016-19)",
            Brand = "Yamaha", Family = "Tracer",
            Blurb = "689 cc 270° parallel twin, 75 PS, 196 kg, half fairing, upright",
            Engine = EngineLayout.ParallelTwin270,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.ParallelTwin,
                Wheelbase = 1.46f, RakeDeg = 24f, Trail = 0.09f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "180/55ZR17", FrontTravel = 0.135f, RearTravel = 0.135f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 17f,
                Seat = new Vector3(0, 0.82f, -0.22f), Grip = new Vector3(0.38f, 1.04f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.08f, 0.22f, 0.7f), Trim = new Color(0.9f, 0.9f, 0.92f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.08f, 0.22f, 0.7f),
            },
            Colours = "",
            WetMass = 196f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.46f, BrakeDecel = 9.5f,
            IdleRpm = 1200f, PeakRpm = 9000f, Redline = 9800f, LaunchRpm = 5000f,
            Torque = new (float, float)[] { (1200f, 37.4f), (3250f, 55.8f), (6500f, 68f), (7750f, 64.5f), (9000f, 58.4f), (9800f, 49.6f) },
            Gears = new[] { 2.846f, 2.125f, 1.632f, 1.3f, 1.091f, 0.964f }, Primary = 1.925f, FinalDrive = 2.812f,
        },
        // ---- 143 ----
        // Yamaha Tracer 7 (2020+). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "TRACER7-2020" (Tracer 7 (2020+), GT see notes).
        // 689 cc 270° parallel twin, 73 PS at 8,750 rpm, 68 N·m at 6,500; 6 gears 2.846-0.964, primary 1.925, final 2.812; kerb 196 kg; wheelbase 1460 mm; rake 24.8°, trail 90 mm; 120/70ZR17 + 180/55ZR17.
        // Reference: 200 km/h (claimed (inSella data sheet)), 0-100 - s.
        // https://bikebros.co.jp/catalog/2/999_16/
        // https://bikebros.co.jp/catalog/2/999_127/
        // https://www.insella.it/da-sapere/yamaha-tracer-7-y-amt-quanto-fa-il-cambio-robotizzato-73727
        // Assumed: redline 9,550; primary 77/40 = 1.925 as the MT-07 (same CP2 engine; not in the dataset); seat 820 mm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.46 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1200, launch 4800; livery from "blue with black frame and blue wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha Tracer 7 (2020+)",
            Brand = "Yamaha", Family = "Tracer",
            Blurb = "689 cc 270° parallel twin, 73 PS, 196 kg, half fairing, upright",
            Engine = EngineLayout.ParallelTwin270,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.ParallelTwin,
                Wheelbase = 1.46f, RakeDeg = 24.8f, Trail = 0.09f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "180/55ZR17", FrontTravel = 0.135f, RearTravel = 0.135f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 17f,
                Seat = new Vector3(0, 0.82f, -0.22f), Grip = new Vector3(0.38f, 1.04f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.08f, 0.22f, 0.7f), Trim = new Color(0.9f, 0.9f, 0.92f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.08f, 0.22f, 0.7f),
            },
            Colours = "",
            WetMass = 196f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.46f, BrakeDecel = 9.5f,
            IdleRpm = 1200f, PeakRpm = 8750f, Redline = 9550f, LaunchRpm = 4800f,
            Torque = new (float, float)[] { (1200f, 37.4f), (3250f, 55.8f), (6500f, 68f), (7625f, 64.7f), (8750f, 58.9f), (9550f, 50.1f) },
            Gears = new[] { 2.846f, 2.125f, 1.632f, 1.3f, 1.091f, 0.964f }, Primary = 1.925f, FinalDrive = 2.812f,
            RefZeroTo100 = 0f, RefTopKmh = 200f,
        },
        // ---- 144 ----
        // Yamaha Tracer 9 (2021+). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "TRACER9-2021" (Tracer 9 (2021+)).
        // 890 cc CP3 triple, 119 PS at 10,000 rpm, 93 N·m at 7,000; 6 gears 2.571-1.037, primary 1.680, final 2.812; kerb 213 kg; wheelbase 1500 mm; rake 25.0°, trail 108 mm; 120/70ZR17 + 180/55ZR17.
        // https://www.bikebros.co.jp/catalog/2/999_126/16369/
        // https://global.yamaha-motor.com/jp/news/2020/1118/tracer9.html
        // Assumed: kerb 213 kg: the GT's 220 less its cases and semi-active parts (estimate); CdA 0.59 m² for the Tracer 900 / 9, fitted to the Tracer 9 GT's measured 214 km/h (the generic 0.46 gave 233); redline 11,000; seat 820 mm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.59 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1250, launch 5500; livery from "dark blue with grey/white accents, black frame, blue wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha Tracer 9 (2021+)",
            Brand = "Yamaha", Family = "Tracer",
            Blurb = "890 cc CP3 triple, 119 PS, 213 kg, half fairing, upright",
            Engine = EngineLayout.Triple,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.Triple,
                Wheelbase = 1.5f, RakeDeg = 25f, Trail = 0.108f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "180/55ZR17", FrontTravel = 0.135f, RearTravel = 0.135f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 18f,
                Seat = new Vector3(0, 0.82f, -0.22f), Grip = new Vector3(0.38f, 1.04f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.08f, 0.22f, 0.7f), Trim = new Color(0.9f, 0.9f, 0.92f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.08f, 0.22f, 0.7f),
            },
            Colours = "",
            WetMass = 213f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.59f, BrakeDecel = 9.5f,
            IdleRpm = 1250f, PeakRpm = 10000f, Redline = 11000f, LaunchRpm = 5500f,
            Torque = new (float, float)[] { (1250f, 51.2f), (3500f, 76.3f), (7000f, 93f), (8500f, 90.1f), (10000f, 83.6f), (11000f, 71f) },
            Gears = new[] { 2.571f, 1.947f, 1.619f, 1.38f, 1.19f, 1.037f }, Primary = 1.68f, FinalDrive = 2.812f,
        },
        // ---- 145 ----
        // Yamaha Tracer 9 GT (2021+). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "TRACER9GT-2021" (Tracer 9 GT (2021+)).
        // 890 cc CP3 triple, 119 PS at 10,000 rpm, 93 N·m at 7,000; 6 gears 2.571-1.037, primary 1.680, final 2.812; kerb 220 kg; wheelbase 1500 mm; rake 25.0°, trail 108 mm; 120/70ZR17 + 180/55ZR17.
        // Reference: 214.1 km/h (measured (inSella, Italy, 2022 Tracer 9 GT)), 0-100 3.1 s.
        // https://www.bikebros.co.jp/catalog/2/999_126/16369/
        // https://global.yamaha-motor.com/jp/news/2020/1118/tracer9.html
        // https://www.insella.it/da-sapere/vivere-moto/yamaha-tracer9-quanto-fa-ecco-tutti-dati-veri-61131
        // Assumed: CdA 0.59 m² for the Tracer 900 / 9, fitted to the Tracer 9 GT's measured 214 km/h (the generic 0.46 gave 233); redline 11,000; seat 820 mm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.59 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1250, launch 5500; livery from "blue with silver-grey flanks, black frame, blue wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha Tracer 9 GT (2021+)",
            Brand = "Yamaha", Family = "Tracer",
            Blurb = "890 cc CP3 triple, 119 PS, 220 kg, half fairing, upright",
            Engine = EngineLayout.Triple,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.Triple,
                Wheelbase = 1.5f, RakeDeg = 25f, Trail = 0.108f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "180/55ZR17", FrontTravel = 0.135f, RearTravel = 0.135f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 18f,
                Seat = new Vector3(0, 0.82f, -0.22f), Grip = new Vector3(0.38f, 1.04f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.08f, 0.22f, 0.7f), Trim = new Color(0.9f, 0.9f, 0.92f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.08f, 0.22f, 0.7f),
            },
            Colours = "",
            WetMass = 220f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.59f, BrakeDecel = 9.5f,
            IdleRpm = 1250f, PeakRpm = 10000f, Redline = 11000f, LaunchRpm = 5500f,
            Torque = new (float, float)[] { (1250f, 51.2f), (3500f, 76.3f), (7000f, 93f), (8500f, 90.1f), (10000f, 83.6f), (11000f, 71f) },
            Gears = new[] { 2.571f, 1.947f, 1.619f, 1.38f, 1.19f, 1.037f }, Primary = 1.68f, FinalDrive = 2.812f,
            RefZeroTo100 = 3.1f, RefTopKmh = 214.1f,
        },
        // ---- 146 ----
        // Yamaha Tracer 9 GT+ (2023+). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "TRACER9GTPLUS-2023" (Tracer 9 GT+ (2023+)).
        // 890 cc CP3 triple, 119 PS at 10,000 rpm, 93 N·m at 7,000; 6 gears 2.571-1.037, primary 1.680, final 2.812; kerb 223 kg; wheelbase 1500 mm; rake 25.0°, trail 108 mm; 120/70ZR17 + 180/55ZR17.
        // https://www.bikebros.co.jp/catalog/2/999_126/16369/
        // https://www.insella.it/da-sapere/vivere-moto/yamaha-tracer9-quanto-fa-ecco-tutti-dati-veri-61131
        // Assumed: CdA 0.59 m² for the Tracer 900 / 9, fitted to the Tracer 9 GT's measured 214 km/h (the generic 0.46 gave 233); redline 11,000; seat 820 mm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.59 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1250, launch 5500; livery from "dark grey/black with silver accents, black frame and black wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Yamaha Tracer 9 GT+ (2023+)",
            Brand = "Yamaha", Family = "Tracer",
            Blurb = "890 cc CP3 triple, 119 PS, 223 kg, half fairing, upright",
            Engine = EngineLayout.Triple,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.Triple,
                Wheelbase = 1.5f, RakeDeg = 25f, Trail = 0.108f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "180/55ZR17", FrontTravel = 0.135f, RearTravel = 0.135f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 18f,
                Seat = new Vector3(0, 0.82f, -0.22f), Grip = new Vector3(0.38f, 1.04f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.4f, 0.41f, 0.44f), Trim = new Color(0.1f, 0.1f, 0.11f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 223f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.59f, BrakeDecel = 9.5f,
            IdleRpm = 1250f, PeakRpm = 10000f, Redline = 11000f, LaunchRpm = 5500f,
            Torque = new (float, float)[] { (1250f, 51.2f), (3500f, 76.3f), (7000f, 93f), (8500f, 90.1f), (10000f, 83.6f), (11000f, 71f) },
            Gears = new[] { 2.571f, 1.947f, 1.619f, 1.38f, 1.19f, 1.037f }, Primary = 1.68f, FinalDrive = 2.812f,
        },
        // ---- 147 ----
        // Kawasaki Versys 650 (2007-09). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "KLE650-2007" (Versys (2007-2009)).
        // 649 cc 180° parallel twin, 64 PS at 8,000 rpm, 61 N·m at 6,800; 6 gears 2.438-0.852, primary 2.095, final 2.873; kerb 206 kg; wheelbase 1415 mm; rake 25.0°, trail 108 mm; 120/70ZR17 + 160/60ZR17.
        // https://www.ultimatespecs.com/motorcycles-specs/kawasaki/kawasaki-versys-2007
        // https://en.wikipedia.org/wiki/Kawasaki_Versys_650
        // https://bikebros.co.jp/catalog/4/74_1
        // Assumed: redline 8,800; gear ratios borrowed from KLE650-2015 (spread only: the overall gearing is fitted below); primary 2.095 and final 2.873: the overall top gear fitted to 193 km/h at 105% of the peak-power rpm; seat 820 mm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.46 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1200, launch 4400; livery from "lime green with black frame and black wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Kawasaki Versys 650 (2007-09)",
            Brand = "Kawasaki", Family = "Versys 650",
            Blurb = "649 cc 180° parallel twin, 64 PS, 206 kg, half fairing, upright",
            Engine = EngineLayout.ParallelTwin180,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.ParallelTwin,
                Wheelbase = 1.415f, RakeDeg = 25f, Trail = 0.108f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "160/60ZR17", FrontTravel = 0.135f, RearTravel = 0.135f,
                FrontDiscs = 2, FrontDiscMm = 300f,
                Seat = new Vector3(0, 0.82f, -0.22f), Grip = new Vector3(0.38f, 1.04f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.42f, 0.8f, 0.1f), Trim = new Color(0.08f, 0.08f, 0.09f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 206f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.46f, BrakeDecel = 9.5f,
            IdleRpm = 1200f, PeakRpm = 8000f, Redline = 8800f, LaunchRpm = 4400f,
            Torque = new (float, float)[] { (1200f, 33.6f), (3400f, 50f), (6800f, 61f), (7400f, 59.7f), (8000f, 56.1f), (8800f, 47.7f) },
            Gears = new[] { 2.438f, 1.714f, 1.333f, 1.111f, 0.966f, 0.852f }, Primary = 2.095f, FinalDrive = 2.8726f,
        },
        // ---- 148 ----
        // Kawasaki Versys 650 (2010-14). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "KLE650-2010" (Versys 650 (2010-2014)).
        // 649 cc 180° parallel twin, 64 PS at 8,000 rpm, 61 N·m at 6,800; 6 gears 2.438-0.852, primary 2.095, final 2.975; kerb 206 kg; wheelbase 1415 mm; rake 25.0°, trail 108 mm; 120/70ZR17 + 160/60ZR17.
        // Reference: 186 km/h (claimed (database figure)), 0-100 - s.
        // https://en.wikipedia.org/wiki/Kawasaki_Versys_650
        // https://bikebros.co.jp/catalog/4/74_1
        // https://www.motorradundreisen.de/motorraddatenbank/kawasaki/versys-650-2021-3425.html
        // Assumed: kerb 206 kg as the 2007-09 Versys (same frame and engine); redline 8,800; gear ratios borrowed from KLE650-2015 (spread only: the overall gearing is fitted below); primary 2.095 and final 2.975: the overall top gear fitted to 186 km/h at 105% of the peak-power rpm; seat 820 mm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.46 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1200, launch 4400; livery from "lime green with black frame and black wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Kawasaki Versys 650 (2010-14)",
            Brand = "Kawasaki", Family = "Versys 650",
            Blurb = "649 cc 180° parallel twin, 64 PS, 206 kg, half fairing, upright",
            Engine = EngineLayout.ParallelTwin180,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.ParallelTwin,
                Wheelbase = 1.415f, RakeDeg = 25f, Trail = 0.108f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "160/60ZR17", FrontTravel = 0.135f, RearTravel = 0.135f,
                FrontDiscs = 2, FrontDiscMm = 300f,
                Seat = new Vector3(0, 0.82f, -0.22f), Grip = new Vector3(0.38f, 1.04f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.42f, 0.8f, 0.1f), Trim = new Color(0.08f, 0.08f, 0.09f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 206f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.46f, BrakeDecel = 9.5f,
            IdleRpm = 1200f, PeakRpm = 8000f, Redline = 8800f, LaunchRpm = 4400f,
            Torque = new (float, float)[] { (1200f, 33.6f), (3400f, 50f), (6800f, 61f), (7400f, 59.7f), (8000f, 56.1f), (8800f, 47.7f) },
            Gears = new[] { 2.438f, 1.714f, 1.333f, 1.111f, 0.966f, 0.852f }, Primary = 2.095f, FinalDrive = 2.975f,
            RefZeroTo100 = 0f, RefTopKmh = 186f,
        },
        // ---- 149 ----
        // Kawasaki Versys 650 (2015-21). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "KLE650-2015" (Versys 650 (2015-2021)).
        // 649 cc 180° parallel twin, 70 PS at 8,500 rpm, 64 N·m at 7,000; 6 gears 2.438-0.852, primary 2.095, final 3.067; kerb 216 kg; wheelbase 1415 mm; rake 25.0°, trail 110 mm; 120/70ZR17 + 160/60ZR17.
        // Reference: 186 km/h (claimed (database figure; Kawasaki quoted about 185 per MOTORRAD online)), 0-100 - s.
        // https://www.motorcyclespecs.co.za/model/kawasaki/kawasaki_versys_650_15.html
        // https://www.motorcyclespecs.co.za/model/kawasaki/kawasaki_versys%20650_20.html
        // https://www.cycleworld.com/story/bikes/2021-kawasaki-versys-650-lt-dyno-test
        // Assumed: redline 9,300; seat 820 mm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.46 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1200, launch 4700; livery from "lime green with black frame, black engine and black wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Kawasaki Versys 650 (2015-21)",
            Brand = "Kawasaki", Family = "Versys 650",
            Blurb = "649 cc 180° parallel twin, 70 PS, 216 kg, half fairing, upright",
            Engine = EngineLayout.ParallelTwin180,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.ParallelTwin,
                Wheelbase = 1.415f, RakeDeg = 25f, Trail = 0.11f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "160/60ZR17", FrontTravel = 0.15f, RearTravel = 0.145f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 21f,
                Seat = new Vector3(0, 0.82f, -0.22f), Grip = new Vector3(0.38f, 1.04f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.42f, 0.8f, 0.1f), Trim = new Color(0.08f, 0.08f, 0.09f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 216f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.46f, BrakeDecel = 9.5f,
            IdleRpm = 1200f, PeakRpm = 8500f, Redline = 9300f, LaunchRpm = 4700f,
            Torque = new (float, float)[] { (1200f, 35.2f), (3500f, 52.5f), (7000f, 64f), (7750f, 62.1f), (8500f, 57.8f), (9300f, 49.1f) },
            Gears = new[] { 2.438f, 1.714f, 1.333f, 1.111f, 0.966f, 0.852f }, Primary = 2.095f, FinalDrive = 3.067f,
            RefZeroTo100 = 0f, RefTopKmh = 186f,
        },
        // ---- 150 ----
        // Kawasaki Versys 650 (2022+). docs/data/yamaha_tenere_tracer_kawasaki_versys_specs.json "KLE650-2022" (Versys 650 (2022+)).
        // 649 cc 180° parallel twin, 67 PS at 8,500 rpm, 61 N·m at 7,000; 6 gears 2.438-0.852, primary 2.095, final 3.067; kerb 219 kg; wheelbase 1415 mm; rake 25.0°, trail 108 mm; 120/70ZR17 + 160/60ZR17.
        // Reference: 186 km/h (claimed (database figure)), 0-100 - s.
        // https://bikebros.co.jp/catalog/4/74_1
        // https://en.wikipedia.org/wiki/Kawasaki_Versys_650
        // https://www.motorradundreisen.de/motorraddatenbank/kawasaki/versys-650-2021-3425.html
        // Assumed: redline 9,300; seat 820 mm; the sporttouring values (CG 0.66 m, 50% rear, CdA 0.46 m², grip 1.1, 48° lean, brakes 9.5 m/s², riding position), the torque curve between the peaks, idle 1200, launch 4700; livery from "lime green with black frame and black wheels (unverified)".
        new MotorbikeSpec
        {
            Label = "Kawasaki Versys 650 (2022+)",
            Brand = "Kawasaki", Family = "Versys 650",
            Blurb = "649 cc 180° parallel twin, 67 PS, 219 kg, half fairing, upright",
            Engine = EngineLayout.ParallelTwin180,
            Look = new MotoLook
            {
                Style = MotoStyle.SportTouring, EngineShape = MotoEngineShape.ParallelTwin,
                Wheelbase = 1.415f, RakeDeg = 25f, Trail = 0.108f, ForkLength = 0.68f,
                FrontTyre = "120/70ZR17", RearTyre = "160/60ZR17", FrontTravel = 0.15f, RearTravel = 0.145f,
                FrontDiscs = 2, FrontDiscMm = 300f, TankLitres = 20f,
                Seat = new Vector3(0, 0.82f, -0.22f), Grip = new Vector3(0.38f, 1.04f, 0.28f), Peg = new Vector3(0.18f, 0.37f, -0.1f),
                Paint = new Color(0.42f, 0.8f, 0.1f), Trim = new Color(0.08f, 0.08f, 0.09f), Frame = new Color(0.1f, 0.1f, 0.11f), Wheel = new Color(0.1f, 0.1f, 0.11f),
            },
            Colours = "",
            WetMass = 219f, CgHeight = 0.66f, RearShare = 0.5f, Grip = 1.1f, MaxLean = Mathf.DegToRad(48f),
            DragArea = 0.46f, BrakeDecel = 9.5f,
            IdleRpm = 1200f, PeakRpm = 8500f, Redline = 9300f, LaunchRpm = 4700f,
            Torque = new (float, float)[] { (1200f, 33.6f), (3500f, 50f), (7000f, 61f), (7750f, 59.3f), (8500f, 55.4f), (9300f, 47.1f) },
            Gears = new[] { 2.438f, 1.714f, 1.333f, 1.111f, 0.966f, 0.852f }, Primary = 2.095f, FinalDrive = 3.067f,
            RefZeroTo100 = 0f, RefTopKmh = 186f,
        },
    };
}
