namespace UnitSport.Tools.RoadGen.Export;

using System.Globalization;
using System.Text;
using UnitSport.Tools.RoadGen.Geometry;
using UnitSport.Tools.RoadGen.Junctions;
using UnitSport.Tools.RoadGen.Meshing;

/// <summary>
/// Wavefront OBJ export, so the surfaces can be opened in any 3D viewer without the game.
///
/// <para>
/// Axis convention matches the runtime: X east, Y up, Z south — so plan-view northing becomes
/// −Z. Height comes from a caller-supplied sampler, because RoadGen deliberately knows nothing
/// about terrain; feeding it the real <c>ChunkGrid</c> drapes the network, feeding it
/// <c>_ => 0</c> gives a flat sheet that is easier to inspect.
/// </para>
/// </summary>
public static class ObjWriter
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    public static void Write(string path,
        IReadOnlyList<Ribbon> ribbons,
        IReadOnlyList<Junction> junctions,
        IReadOnlyDictionary<int, List<MarkingLine>> markings,
        Func<Vec2, double>? height = null,
        double markingLift = 0.01)
    {
        height ??= _ => 0.0;

        var sb = new StringBuilder();
        sb.AppendLine("# generated by tools/RoadGen");
        sb.AppendLine("# X east, Y up, Z south (northing negated), metres");
        int vertexBase = 1;

        sb.AppendLine("o carriageway");
        foreach (var ribbon in ribbons)
        {
            if (ribbon.IsEmpty) continue;
            int count = ribbon.Stations.Count;

            for (int i = 0; i < count; i++)
            {
                Vertex(sb, ribbon.Left[i], height(ribbon.Left[i]));
                Vertex(sb, ribbon.Right[i], height(ribbon.Right[i]));
            }
            for (int i = 0; i < count - 1; i++)
            {
                int a = vertexBase + i * 2;
                sb.AppendLine($"f {a} {a + 1} {a + 3}");
                sb.AppendLine($"f {a} {a + 3} {a + 2}");
            }
            vertexBase += count * 2;
        }

        sb.AppendLine("o junctions");
        foreach (var junction in junctions)
        {
            foreach (var v in junction.Vertices) Vertex(sb, v, height(v));
            for (int i = 0; i + 2 < junction.Triangles.Count; i += 3)
                sb.AppendLine($"f {vertexBase + junction.Triangles[i]} " +
                              $"{vertexBase + junction.Triangles[i + 1]} " +
                              $"{vertexBase + junction.Triangles[i + 2]}");
            vertexBase += junction.Vertices.Count;
        }

        sb.AppendLine("o markings");
        foreach (var (_, lines) in markings)
        foreach (var line in lines)
        {
            if (line.Points.Count < 2) continue;
            double half = line.Width * 0.5;

            for (int i = 0; i < line.Points.Count; i++)
            {
                var forward = i == 0 ? line.Points[1] - line.Points[0]
                    : i == line.Points.Count - 1 ? line.Points[^1] - line.Points[^2]
                    : line.Points[i + 1] - line.Points[i - 1];
                var normal = forward.Normalized().Perp * half;
                var l = line.Points[i] + normal;
                var r = line.Points[i] - normal;
                Vertex(sb, l, height(l) + markingLift);
                Vertex(sb, r, height(r) + markingLift);
            }
            for (int i = 0; i < line.Points.Count - 1; i++)
            {
                int a = vertexBase + i * 2;
                sb.AppendLine($"f {a} {a + 1} {a + 3}");
                sb.AppendLine($"f {a} {a + 3} {a + 2}");
            }
            vertexBase += line.Points.Count * 2;
        }

        File.WriteAllText(path, sb.ToString());
    }

    private static void Vertex(StringBuilder sb, Vec2 p, double y) =>
        sb.AppendLine($"v {p.X.ToString("0.####", Inv)} {y.ToString("0.####", Inv)} {(-p.Y).ToString("0.####", Inv)}");
}
